language: objective-c

before_script:
- chmod +x scripts/travis/add-key.sh
- chmod +x scripts/travis/remove-key.sh
- ./scripts/travis/add-key.sh
after_script:
- ./scripts/travis/remove-key.sh

script: xcodebuild -workspace Travis-Demo-ObjC.xcworkspace -scheme Travis-Demo-ObjC