language: objective-c

before_script:
- chmod +x scripts/travis/add-key.sh
- chmod +x scripts/travis/remove-key.sh
- ./scripts/travis/add-key.sh
after_script:
- ./scripts/travis/remove-key.sh

script: xctool -workspace Travis-Demo-ObjC.xcworkspace -scheme Travis-Demo-ObjC -configuration Debug

env:
  global:
  - DEVELOPER_NAME="iPhone Distribution: Spottinstyle limited (K28S6JSF7L)"
  - PROFILE_UUID=7f062407-cbfe-4611-937b-f70ec1ed4549